spring.application.name=ticketing-backend
ticketspot.cli.enabled=false

spring.datasource.url=${TICKETSPOT_DB_URL:jdbc:postgresql://localhost:5433/ticketing_system}
spring.datasource.username=${TICKETSPOT_DB_USERNAME:postgres}
spring.datasource.password=${TICKETSPOT_DB_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect